import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AuthorsProvider } from "./context/AuthorsContext";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased`}>
        <AuthorsProvider>
          {" "}
          {/* envolver toda la app con el proveedor de contexto para que todos los hijos tengan acceso a los autores */}
          {children}
        </AuthorsProvider>
      </body>
    </html>
  );
}
